# Generated by Django 5.2.7 on 2025-10-15 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cervical", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrecord",
            name="contraception",
        ),
        migrations.RemoveField(
            model_name="patientrecord",
            name="referred",
        ),
        migrations.RemoveField(
            model_name="patientrecord",
            name="sexual_history",
        ),
        migrations.RemoveField(
            model_name="patientrecord",
            name="smoking",
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="contraception_years",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Hormonal Contraceptives (years)"
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="referral_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="referral_status",
            field=models.CharField(
                choices=[("N", "None"), ("R", "Referred"), ("C", "Consulted")],
                default="N",
                max_length=1,
                verbose_name="Referral Status",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="sexual_partners",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of sexual partners"
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="smoking_years",
            field=models.PositiveIntegerField(default=0, verbose_name="Smokes (years)"),
        ),
        migrations.AlterField(
            model_name="patientrecord",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientrecord",
            name="hpv_result",
            field=models.CharField(
                choices=[
                    ("Positive", "Positive"),
                    ("Negative", "Negative"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="PatientDoubt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_answered", models.BooleanField(default=False)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doubts",
                        to="cervical.patientrecord",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doubts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Doubt",
                "verbose_name_plural": "Patient Doubts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="PatientMessage",
        ),
    ]
