# Generated by Django 5.0.14 on 2025-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervical', '0002_remove_patientrecord_contraception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='clinical_risk_score',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=24, null=True),
        ),
    ]
