# Generated by Django 6.0 on 2026-01-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervical', '0003_alter_patientrecord_clinical_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='shap_explanation',
            field=models.TextField(blank=True),
        ),
    ]
