# Generated by Django 5.2.6 on 2026-04-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervical', '0004_patientrecord_shap_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='dx_cancer',
            field=models.BooleanField(default=False, verbose_name='Previous Cancer Diagnosis'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='first_sexual_intercourse',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age of first sexual intercourse'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='iud_years',
            field=models.PositiveIntegerField(default=0, verbose_name='IUD (years)'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='num_pregnancies',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of pregnancies'),
        ),
    ]
