# Generated by Django 5.2.6 on 2026-04-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cervical', '0005_patientrecord_dx_cancer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='dx_cancer',
        ),
    ]
